version: "1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: e-commerce-app
    container_name: e-commerce-app-container

    ports:
    - "5000:5000"

    env_file:
    - .env

    restart: unless-stopped
